### PR TITLE
chore: rename force flag to restart for copilot svc deploy and copilot deploy

### PR DESCRIPTION
**Pull request by KollaAdithya**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by bvtujo — COMMENTED** [review]
Is this fully descriptive of the use cases, though?
It seems like the behavior is:
a) if there is an existing deployment to that service, cancel it and restart
b) If there are no immediate changes, redeploy the stack anyway by regenerating the random ID output. 

Are we getting rid of b)?

**Comment by iamhopaul123** [comment]
+1 to Austin's feedback. Maybe we should use ECS's terminology [`--force-new-deployment`](https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html) to make this flag more specific? What do you all think?

**Comment by dannyrandall** [comment]
i like `--force-new-deployment`! seems as good as any other ideas ¯\_(ツ)_/¯

**Comment by KollaAdithya** [comment]
closing as rename is not required.

**Pull request closed without merging**
