### PR TITLE
feat(pipelines): install Docker in `test_commands` CodeBuild project

### PR DESCRIPTION
**Pull request by huanjani**
If users have their tests configured in containers, they can now use `docker build` commands in the `test_commands` field of the pipeline manifest. 

Addresses #1280.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bvtujo — COMMENTED** [review]
Looks great! Do we need to update any integration tests for this?

**Review by efekarakus — APPROVED** [review]

**Comment by huanjani** [comment]
> Looks great! Do we need to update any integration tests for this?

They're passing locally. I updated the stack/pipeline ones. It'd be nice to eventually test containerized tests where we test `test_commands`.

**Comment by ceagan** [comment]
Suggestion: the environment variable for the AWS_ACCOUNT_ID can also be exposed here like it is for the main build. It could be helpful when pulling images from an ECR private repository, which in turn is helpful to avoid Docker Hub pull limits.

```
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Sub '${AWS::AccountId}'
```

**Review by ceagan — APPROVED** [review]
I was able to pull these changes and test with a sandbox build I've been working on and it works perfectly! Thanks!

**Review by bvtujo — APPROVED** [review]

**Comment by huanjani** [comment]
> Suggestion: the environment variable for the AWS_ACCOUNT_ID can also be exposed here like it is for the main build. It could be helpful when pulling images from an ECR private repository, which in turn is helpful to avoid Docker Hub pull limits.
> 
> ```
>         EnvironmentVariables:
>           - Name: AWS_ACCOUNT_ID
>             Value: !Sub '${AWS::AccountId}'
> ```

Thanks for this suggestion (and for your Gitter post that got this ball rolling)!

**Pull request merged**
