### PR TITLE
feat: Support Podman to build container images

### PR DESCRIPTION
**Pull request by hown3d**
I added an experimental Environment Variable __COPILOT_PODMAN__, that lets users use Podman instead of docker to build their images.
An e2e Test using Podman was also added. It's run after the docker e2e test.

Addresses #3170

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Comment by hown3d** [comment]
I merged upstream into the branch again. Is there something else to be done for review? @Lou1415926 @iamhopaul123

**Comment by efekarakus** [comment]
Hi @hown3d ! 
I'm so sorry that it took this long to reply to you 🙇 thank you very much for the contribution. I've some high level questions before integrating with podman if you don't mind.

1. Do you know of any other tools that integrate with podman? Is there a reason why you preferred environment variable as a way of toggling?   
I'm looking to see if there is a precedent for using env variables to build with podman vs. an option in the manifest such as:
   ```yaml
   image:
     build:
        engine: 'podman' # default is 'docker'
   ```

2. What are the downsides today of just doing `alias docker=podman` like in the [homepage of podman](https://podman.io/)? I'm trying to understand if it's worthwhile adding and maintaining new code in the repo if the mitigation already works for users.

3. How about users that use the [copilot pipelines](https://aws.github.io/copilot-cli/docs/concepts/pipelines/)? `podman` won't be installed in the build project, do we deem it acceptable if the images are build with docker in the pipeline but with podman locally?

If possible a design github issue or commenting on https://github.com/aws/copilot-cli/issues/3170 with the various alternatives would make it easier for us to accept the PR:
> * If you would like to propose a new feature, please open an issue on GitHub with a detailed description. This enables us to collaborate on the feature design more easily and increases the chances that your feature request will be accepted.
> https://github.com/aws/copilot-cli/blob/mainline/CONTRIBUTING.md


Again I'm really sorry about the delay on responding to the PR.

**Comment by nathanpeck** [comment]
It is possible to use Copilot with Podman instead of Docker by running the following on Mac:

```
ln -s /usr/local/bin/podman /usr/local/bin/docker
```

This puts a symlink in place of the Docker binary, which redirects the commands to Podman

**Comment by nathanpeck** [comment]
Unfortunately after some deeper experimentation I found another blocker: Podman and Docker Desktop have differing image digest behavior which is currently breaking the AWS Copilot flow and causing the image references to be broken.

Will continue to look for workarounds to this issue, but in the meantime I have opened an issue on Podman itself: https://github.com/containers/podman/issues/14779

**Comment by efekarakus** [comment]
Hi @hown3d, I'm closing the issue for now as Nathan pointed out we can reroute `docker` to `podman` but even then `digests` don't seem to match. I think if the `--tag` field is used `copilot svc deploy`, copilot won't use the digest sha so there is path to mitigation although not ideal.

**Pull request closed without merging**
