### PR TITLE
chore: allow signals to send after watch flag restarts tasks

### PR DESCRIPTION
**Pull request by CaptainCarpensir**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by KollaAdithya — APPROVED** [review]
Just curious! what ideally cloud be a long term fix for this.

**Comment by KollaAdithya** [comment]
can we change the pr title from `fix` to `chore`

**Review by iamhopaul123 — APPROVED** [review]
Can we change it to "chore"? Since it's not released yet.

**Comment by CaptainCarpensir** [comment]
> Just curious! what ideally cloud be a long term fix for this.

To make `exec` not use an interactive command but...
```
✘ execute command /bin/sh in container web: execute command: InvalidParameterException: Interactive is the only mode supported currently.
```
^ Finding from @iamhopaul123

**Pull request merged**
