### PR TITLE
fix: allow efs volumes to have multiple mount points in a single service

### PR DESCRIPTION
**Pull request by CaptainCarpensir**
This is the easiest possible fix for the issue, we got an internal ticket requesting a fix for this so I wanted to get a basic fix out for review first and iterate if this causes issues.

Related #2921 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by iamhopaul123 — COMMENTED** [review]
LGTM overall! Have you tested applying this new template to an existing deployed workload and see if the update goes through?

**Review by iamhopaul123 — APPROVED** [review]
Can we update the integ test to cover the multiple efs mount points scenario?

**Review by Lou1415926 — APPROVED** [review]

**Comment by wub** [comment]
> LGTM overall! Have you tested applying this new template to an existing deployed workload and see if the update goes through?

@iamhopaul123 @CaptainCarpensir Hey team, how can I manually apply this update to my existing workload? (I still get the error message `✘ validate manifest against environment "staging": validate "storage": cannot specify more than one managed volume per service`)

I've tried to redeploy the pipeline, but maybe that's not the right place. Thanks!

**Comment by iamhopaul123** [comment]
Hello @wub. This should've been fixed in our latest commit. Can you check in your `buildspec.yaml` and see if you are using the latest Copilot version there for the build stage?

**Comment by wub** [comment]
Hey @iamhopaul123, this is the head of our buildspec:

```yaml
version: 0.2
phases:
  install:
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.33.1 -O copilot-linux
```

**Comment by KollaAdithya** [comment]
Hey @wub 

Still Copilot does not support mounting multiple volumes created and managed by Copilot in a single service. This is the [enhancement](https://github.com/aws/copilot-cli/issues/2921) that needs to be done on Copilot end.

But you can configure multiple externally-managed EFS volumes in Copilot. Here is a sample manifest configuration for an external EFS volume.

```
storage:
  volumes:
    externalvolume1:
      path: '/etc/mount1'
      efs:
        id: fs-1234567
    externalvolume2:
      path: '/etc/mount2'
      efs:
        id: fs-4567891
```

**Comment by KollaAdithya** [comment]
Here is a [doc](https://aws.github.io/copilot-cli/docs/developing/storage/#external-efs) that helps on how you can configure external managed EFS volumes in Copilot.

**Pull request merged**
