### PR TITLE
feat(templates): enable deployment circuit breaker for services 

### LINKED ISSUE #1735: Circuit breaker support
As soon as [Circuit Breaker Support](https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/) is available in CloudFormation, Copilot should support it.

### PR DESCRIPTION
**Pull request by efekarakus**
Resolves #1735 

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by kohidave — APPROVED** [review]

**Review by huanjani — APPROVED** [review]

**Review by iamhopaul123 — APPROVED** [review]
LGTM! Do we need to update integ test for this change?

**Comment by efekarakus** [comment]
I checked and didn't seee anything that might break them, but I guess we'll see :D I'll monitor the pipeline

**Comment by mwarkentin** [comment]
@efekarakus We found there to be some issues with the way cloudformation interacts with the circuit breaker (https://github.com/aws/containers-roadmap/issues/1205) outside of copilot. Does copilot deal with this better somehow?

**Comment by efekarakus** [comment]
Hey @mwarkentin ! Copilot v1.2.0 will display deployment progress while running `copilot deploy`, so you'll be able to tell that your service actually rolled back due to the circuit breaker kicking in:

https://user-images.githubusercontent.com/879348/106511118-a4e71380-6484-11eb-8e43-da328bdbfd95.mov

Unfortunately, the resource status will still be `UPDATE_COMPLETE` in CloudFormation. It's just that Copilot won't exit immediately unlike CFN and will keep monitoring the deployment rollout status until the rollout state is no longer in progress.

**Comment by mwarkentin** [comment]
@efekarakus thanks - so basically you highlight what's going on, but the user needs to take some action to get things back to working order (or in sync).

**Comment by efekarakus** [comment]
Yeah, unfortunately that's right

**Comment by mwarkentin** [comment]
No worries! 🤞 that the cloudformation integration improves at some point!

**Pull request merged**
