### PR TITLE
chore: enable and add docs for PlatformArgs

### PR DESCRIPTION
**Pull request by huanjani**
Previously, we would lowercase platform fields to validate them, but not to transform them; consequently, unless values were already lowercased, they would not be recognized and therefore not deployed as non-default. This was not detected as a problem with PlatformStrings because we autogenerated those as lowercase, but this issue became apparent very quickly with PlatformArgs. 

This PR also adds an example of PlatformArgs in the docs. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by efekarakus — APPROVED** [review]
:shipit:

**Comment by efekarakus** [comment]
Why are there 68 commits 😂 ?

**Comment by huanjani** [comment]
> Why are there 68 commits 😂 ?

🙈 🤫

**Review by iamhopaul123 — COMMENTED** [review]
Shall we update the validate function as well?

**Review by iamhopaul123 — APPROVED** [review]

**Pull request merged**
