### PR TITLE
chore: enable version for S3 buckets

### PR DESCRIPTION
**Pull request by KollaAdithya**
It turned out that only the addon S3 and multi pipeline e2e  buckets are currently not version enabled.

And added lifecycle rules for e2e and addons buckets.  

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Comment by huanjani** [comment]
I'm thinking about possible downsides to quietly making this the default setting. https://docs.aws.amazon.com/AmazonS3/latest/userguide/troubleshooting-versioning.html#performance-degradation Size and cost may become large quickly. Should we add an expiration or warning?

**Comment by KollaAdithya** [comment]
I did not know about the downsides of versioning. I will try to list to all the possible proposal in a doc to avoid this.

**Comment by iamhopaul123** [comment]
Very good call! We might want to set expiration date to mitigate the issue if a bucket is only used by Copilot

**Comment by iamhopaul123** [comment]
Also is deletion a potential problem? I remember we need to delete all versions before deleting the bucket

**Comment by KollaAdithya** [comment]
I am just learning about the potential issues on versioning and also writing a doc to test some scenarios and also help us on how we can set lifecycle rules. I will mark this one as draft.

**Review by huanjani — APPROVED** [review]
🚢

**Review by dannyrandall — APPROVED** [review]

**Pull request merged**
