### PR TITLE
chore: use ECR public img for fluent bit

### PR DESCRIPTION
**Pull request by flemzord**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by efekarakus — APPROVED** [review]
Awesome, thank you @flemzord !

**Comment by efekarakus** [comment]
The changes look good to me! looks like there are few CI checks that are failing, once those are addressed we can merge the PR!

**Comment by flemzord** [comment]
@efekarakus Thanks for your feedback, the set should be good this time.

**Review by efekarakus — APPROVED** [review]
Awesome! Looks great 🎉

**Review by iamhopaul123 — APPROVED** [review]

**Comment by Lou1415926** [comment]
This is now released 🎉 in v1.14.0 https://github.com/aws/copilot-cli/releases/tag/v1.14.0 ! Thank you for the contribution!

**Pull request merged**
