### PR TITLE
docs(ja): update for v1.7.0

### PR DESCRIPTION
**Pull request by toricls**
This PR updates the Japanese localized docs based on the changes in the English docs after #2324 to the latest mainline (3781c57) including all v1.7.0 related updates.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by efekarakus — APPROVED** [review]

**Review by Lou1415926 — APPROVED** [review]

**Comment by toricls** [comment]
I'm not sure why the "Semantic Pull Request" check keep failing but my commit message could be the cause? Should I do something to pass it?

**Comment by efekarakus** [comment]
It's indeed the commit message! If you can ammend it and force push again then it should be good! I think the commit needs to starts with `docs` instead of `doc` ☹️ We also added some new changes to the docs today :) for the front page and secrets. Feel free to run the GitHub action once merged!  @toricls

**Comment by toricls** [comment]
Thanks @efekarakus! Then I'll fix it with some additional translations for the new changes in docs you mentioned :)

**Comment by toricls** [comment]
Published! https://github.com/aws/copilot-cli/actions/runs/859712908

**Pull request merged**
