### PR TITLE
build: upgrade lambda runtime from nodejs12.x to nodejs16.x

### LINKED ISSUE #3896: lambda runtime nodejs12.x deprecation
Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 

As of November 14, 2022, Lambda will no longer apply security patches, starting December 14 2022 existing functions cannot be updated.

### PR DESCRIPTION
**Pull request by dclark**
Fixes #3896 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by efekarakus — APPROVED** [review]
Looks great thank you so much @dclark !

**Review by dannyrandall — APPROVED** [review]
looks great! thank you! ❤️

**Comment by toshitanian** [comment]
Hi, thank you guys so much for handling this issue so fast!
The change in the pull request provides us the way to upgrade existing lambda functions?

For example, we have the functions like:
```
CertificateValidationFunct-tLdjfyiFi0FQ:$LATEST
dele-EnvControllerFunction-XHZsU863m7fU:$LATEST
CustomDomainFunction-44P60sgYTTYN:$LATEST
p-DynamicDesiredCountFunct-D4efjMrqTnHu:$LATEST
nigh-EnvControllerFunction-Wd9ibtXqRIgW:$LATEST
proxy-RulePriorityFunction-WVs1UBSFd5VC:$LATEST
prox-EnvControllerFunction-y8FVR5e6Et1Y:$LATEST
DNSDelegationFunction-WaqqFTBDqpJY:$LATEST
```

**Comment by dclark** [comment]
@toshitanian to update the existing functions a deploy is required to both the environment and the services.

For the example of a staging environment with an app called "testapp"

$>copilot env deploy staging
$>copilot app deploy (then select your application and the environment).

This should be repeated for each environment and application.

Within Cloud Formation reviewing the template this should show that the nodejs version has been updated and the lambdas which the template creates.

**Comment by toshitanian** [comment]
@dclark 
Very happy that the change includes lambda update! The procedure looks easy, so we will try soon!
Thank you so much!

**Pull request merged**
