### PR TITLE
chore(cicd): change CodeCommit default branch to 'main'

### PR DESCRIPTION
**Pull request by mikelhamer**
The default branch for new CodeCommit repositories is 'main'. This PR reflects that.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by huanjani** [comment]
Wow, it's great that CodeCommit made this change! Thanks for not only being aware of it, but also creating this PR, @mikelhamer! And you even updated the Japanese version! 👏🏼

**Comment by mikelhamer** [comment]
Thank you! 😃

**Review by iamhopaul123 — APPROVED** [review]
Thank you so much for making this change! Also could you update your commit msg as the title so as to pass the PR check?

**Comment by mikelhamer** [comment]
> 
> 
> Thank you so much for making this change!

@iamhopaul123 you're welcome! It's great being able to contribute to such an awesome tool. 

>could you update your commit msg as the title so as to pass the PR check?

I see you changed the title of the PR, but I'm not quite sure what you mean. There are eight commits, do you mean I should update the commit message for each of them?

**Comment by iamhopaul123** [comment]
Hello @mikelhamer. Sorry for the confusion. Never mind you should be good!

**Review by huanjani — APPROVED** [review]
Looks great! Thank you!

**Review by toricls — APPROVED** [review]

**Pull request merged**
