### PR TITLE
chore: fix example of import-public-subnets

### PR DESCRIPTION
**Pull request by toshitanian**
Fixed typo in `copilot env init` that there's space in subnet id. `subnet -014661ebb7ab8681a `

```bash
$ copilot env init --help
...
  Creates an environment with imported VPC resources.
  `$ copilot env init --import-vpc-id vpc-099c32d2b98cdcf47 \`
  `--import-public-subnets subnet-013e8b691862966cf,subnet -014661ebb7ab8681a \`
  `--import-private-subnets subnet-055fafef48fb3c547,subnet-00c9e76f288363e7f`
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by efekarakus — APPROVED** [review]
Awesome, ty!

**Review by huanjani — APPROVED** [review]

**Review by iamhopaul123 — APPROVED** [review]
Hey @toshitanian. Thank you so much for contributing! Could you also fix the commit so that it can pass our semantic check?

**Comment by toshitanian** [comment]
@iamhopaul123 Sure. Will fix it it and get back to you.

**Comment by toshitanian** [comment]
@iamhopaul123 Fixed it. Although it looks already be merged, just FYI.

**Comment by toricls** [comment]
Thank you @toshitanian for the PR!

**Comment by iamhopaul123** [comment]
Thank you very much @toshitanian !

**Pull request merged**
