### PR TITLE
fix: remove docker runtime version for `test_commands`

### LINKED ISSUE #4721: docker version 18 in buildspec of test_commands gives 'Unknown runtime version'
Hello,

Today I upgraded from 1.20 to 1.27.0. 

I use test_commands for some post deployment steps and that started failing.

The buildspec that fails is
```
version: 0.2
phases:
  install:
      runtime-versions:
        docker: 18
  build:
    commands:
      - yum install -y sudo && yum install -y expect
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.27.0
      - mv ./copilot-linux-v1.27.0 ./copilot-linux
      - chmod +x ./copilot-linux
      - unbuffer ./copilot-linux svc exec -c "python manage.py collectstatic --no-input --skip-checks" -n app -e test --yes
      - unbuffer ./copilot-linux svc exec -c "python manage.py migrate" -n app -e test --yes
```

The error I'm getting with that:
```
[Container] 2023/03/31 18:53:17 Waiting for agent ping
--
2 | [Container] 2023/03/31 18:53:18 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2023/03/31 18:53:21 Phase is DOWNLOAD_SOURCE
4 | [Container] 2023/03/31 18:53:21 CODEBUILD_SRC_DIR=/codebuild/output/src759560563/src
5 | [Container] 2023/03/31 18:53:21 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2023/03/31 18:53:21 No commands found for phase name: install
7 | [Container] 2023/03/31 18:53:21 Setting HTTP client timeout to higher timeout for S3 source
8 | [Container] 2023/03/31 18:53:21 Processing environment variables
9 | [Container] 2023/03/31 18:53:21 Selecting 'docker' runtime version '18' based on manual selections...
10 | [Container] 2023/03/31 18:53:24 Phase complete: DOWNLOAD_SOURCE State: FAILED
11 | [Container] 2023/03/31 18:53:24 Phase context status code: YAML_FILE_ERROR Message: Unknown runtime version named '18' of docker. This build image has the following versions: 20
```

Seems like it sets docker version 18 in the buildspec whereas version 20 is available in the build image.

Comparing that to the generated buildspec for the build stage generated by v1.27.0 that also sets docker to 20 like so:
```
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
      ruby: 3.1
      nodejs: 16
```

I did run `copilot pipeline update` and all the changes for updating to v1.27.0 are committed to main.

Manually changing the buildspec of the build project to use `docker: 20` solves the issue with logging:
```


[Container] 2023/03/31 20:13:20 Waiting for agent ping
--
2 | [Container] 2023/03/31 20:13:21 Waiting for DOWNLOAD_SOURCE
3 | [Container] 2023/03/31 20:13:25 Phase is DOWNLOAD_SOURCE
4 | [Container] 2023/03/31 20:13:25 CODEBUILD_SRC_DIR=/codebuild/output/src591659411/src
5 | [Container] 2023/03/31 20:13:25 YAML location is /codebuild/readonly/buildspec.yml
6 | [Container] 2023/03/31 20:13:25 No commands found for phase name: install
7 | [Container] 2023/03/31 20:13:25 Setting HTTP client timeout to higher timeout for S3 source
8 | [Container] 2023/03/31 20:13:25 Processing environment variables
9 | [Container] 2023/03/31 20:13:25 Selecting 'docker' runtime version '20' based on manual selections...
10 | [Container] 2023/03/31 20:13:25 Running command echo "Specifying docker version in buildspec is deprecated. Using docker $DOCKER_VERSION"
11 | Specifying docker version in buildspec is deprecated. Using docker 20.10.22
```

### PR DESCRIPTION
**Pull request by 0xO0O0**
Updates docker version from 18 --> 20

Fixes #4721

To address a requirement when running test_commands

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Comment by Lou1415926** [comment]
Hey @0xO0O0! Copilot loves external contributions  Thank you very much ❤️!!

What do you think of @efekarakus's proposal here https://github.com/aws/copilot-cli/issues/4721#issuecomment-1492703496? If you think it sounds good, instead of bumping `docker` from `18` to `20`, can we remove the line?

We will need to apply the same changes in five places:
1. The actual change: https://github.com/aws/copilot-cli/blob/e1afe3976229284a680ae59d6be4b6a6dd0478b5/internal/pkg/template/templates/cicd/pipeline_cfn.yml#L304
2. `bb`, `cc`, and `dd` (the three files that you've changed in this PR) to pass the tests
3. https://github.com/aws/copilot-cli/blob/8b4d37eb7cf9455341e08e6f5fff6000a7a9654f/internal/pkg/deploy/cloudformation/stack/testdata/pipeline/gh_template.yaml#L244 and https://github.com/aws/copilot-cli/blob/8b4d37eb7cf9455341e08e6f5fff6000a7a9654f/internal/pkg/deploy/cloudformation/stack/testdata/pipeline/gh_template.yaml#L244 also for the testing purpose

Thank you again!!!

**Comment by 0xO0O0** [comment]
@Lou1415926 very helpful, thank you!  One thing, you posted the gh_template.yaml file twice, was there a third file that also needed updating ?

**Comment by Lou1415926** [comment]
ohh sorry one of the `gh_template.yml` was meant to be `gvv1_template.yml`!
https://github.com/aws/copilot-cli/blob/8b4d37eb7cf9455341e08e6f5fff6000a7a9654f/internal/pkg/deploy/cloudformation/stack/testdata/pipeline/ghv1_template.yml#L217

**Comment by 0xO0O0** [comment]
updated!

**Comment by 0xO0O0** [comment]
If the docker version is no longer required, removing would be a good move. Let me know if that's the direction we want to move in and I'll update the pr.

**Comment by efekarakus** [comment]
@0xO0O0 

> If the docker version is no longer required, removing would be a good move. Let me know if that's the direction we want to move in and I'll update the pr.

That would be awesome, if you don't mind just deleting the `install` phase 🙏

**Review by paragbhingre — APPROVED** [review]
Thank you so much for your contribution ❤️

**Review by efekarakus — APPROVED** [review]
Thank you!!

**Comment by KollaAdithya** [comment]
Fix is now released in v1.28 https://github.com/aws/copilot-cli/releases/tag/v1.28.0. Thanks @0xO0O0 for reporting and contribution!

**Pull request merged**
