### PR TITLE
chore: Update README.md

### PR DESCRIPTION
**Pull request by bkaws**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the Apache 2.0 License.

### CODE REVIEW

**Review by Madrigal — APPROVED** [review]

**Review by wty-Bryant — APPROVED** [review]

**Comment by SoundsSerious** [comment]
@build-with-aws-copilot  would be nice to know if aws is or is not going to retire this codebase

**Comment by jeffc-dev** [comment]
@bkaws Can you provide an update as to the status of this project?

Should people be migrating off of Copilot?

**Comment by wub** [comment]
Hey @bkaws and @Madrigal, can anyone from AWS please comment on the future of Copilot? We run our entire SaaS on Copilot, and it would be great to know if we should invest our efforts elsewhere. Thank you.

**Comment by jeffc-dev** [comment]
Hoping to hear something from @bkaws or @Madrigal about this...

At this point, though, I think I'm probably going to go with a non-AWS solution for my needs.

**Comment by afgallo** [comment]
Has anyone found a suitable replacement to Copilot?

**Comment by SoundsSerious** [comment]
@afgallo I am actively working to replace it using terraform. Its way harder timewise but its somewhat of a standard.

A solution for creating terraform from copilot: 
1. for each an `environment` and each `service` use the `cli: package` commands to create cloud formation.
2. using a utility like `cf2tf` you can convert like 80-90% of the app to terraform and then there's some clean up to do.

You can also package pipelines to keep everything the same for each environment, as well but I am just creating the one terraform environment an using variables to segment environments and other features / config

Instead we are using github actions to build images and deploy the terraform

**Comment by afgallo** [comment]
@SoundsSerious terraform is a solid choice. I've been considering something different, leveraging our existing CloudFormation templates and migrate infra related components (i.e mostly copilot environment stuff) to [Spectre](https://github.com/Sceptre/sceptre) and use good old EC2 instances with [Kamal](https://kamal-deploy.org/).

**Comment by ejunker** [comment]
I have not used it but another alternative to look into would be sst which supports ECS Fargate using their cluster component https://sst.dev/docs/component/aws/cluster

**Pull request merged**
