### PR TITLE
fix(pipeline): manifest env override won't work

### LINKED ISSUE #1458: Env specific environment variables within pipelines
My apologies if I'm missing something here.

We have setup a 2 stage pipeline, `staging` and `production` concerning a single app called `api`. Within our manifest we utilise the `environments` key to describe different environment variables depending on the copilot environment.

When testing this out via `copilot svc package` command the CloudFormation correctly outputs the correct variable values depending on the environment given.

Within the `buildspec.yml` this package command in run for each environment, outputting `api.stack.yml` and a `api-[env].params.json` file. The `api.stack.yml` file is overwritten each loop, leaving the last environment winning. This leaves all stages of the pipeline using the environment variables using a single environment's config.

### LINKED ISSUE #1535: Incorrect enviromnent variables and secrets in test task definition
I used my company test aws account to initialize copilot with test and a prod env with production aws account.

Here is the simplified manifest.yml

```
# The manifest for the "core-system" service.
# Read the full specification for the "Load Balanced Web Service" type at:
#  https://github.com/aws/copilot-cli/wiki/Manifests#load-balanced-web-svc

# Your service name will be used in naming your resources like log groups, ECS services, etc.
name: core-system
# The "architecture" of the service you're running.
type: Load Balanced Web Service

image:
  # Docker build arguments. You can specify additional overrides here. Supported: dockerfile, context, args
  build: Dockerfile
  # Port exposed through your container to route traffic to it.
  port: 80

http:
  # Requests to this path will be forwarded to your service. 
  # To match all requests you can use the "/" path. 
  path: '/'
  # You can specify a custom health check path. The default is "/"
  healthcheck: '/healthcheck'
  # You can enable sticky sessions.
  # stickiness: true

# Number of CPU units for the task.
cpu: 256
# Amount of memory in MiB used by the task.
memory: 512
# Number of tasks that should be running in your service.
count: 1

# Optional fields for more advanced use-cases.
#
variables:                    # Pass environment variables as key value pairs.
  APP_NAME: core-system

secrets:              

environments:
  test:
    variables:
      APP_ENV: production
      APP_URL: https://dev.core-system.test.url
    secrets:
      APP_KEY: CORE_TEST_APP_KEY
  prod:
    variables:
      APP_ENV: production
      APP_URL: https://dev.core-system.production.url
    secrets:
      APP_KEY: CORE_APP_KEY
```

````
# This YAML file defines the relationship and deployment ordering of your environments.

# The name of the pipeline
name: pipeline-loyal-LUPARG-loyalty

# The version of the schema used in this template
version: 1

# This section defines the source artifacts.
source:
  # The name of the provider that is used to store the source artifacts.
  provider: GitHub
  # Additional properties that further specifies the exact location
  # the artifacts should be sourced from. For example, the GitHub provider
  # has the following properties: repository, branch.
  properties:
    access_token_secret: github-token-core-system
    branch: master
    repository: https://github.com/****/****

# The deployment section defines the order the pipeline will deploy
# to your environments.
stages:
    - # The name of the environment to deploy to.
      name: test
      # Optional: flag for manual approval action before deployment.
      # requires_approval: true
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]

    - # The name of the environment to deploy to.
      name: prod
      # Optional: flag for manual approval action before deployment.
      requires_approval: true
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]

```


I can successfully deploy from the cli to both test and prod.

But the code pipeline fails due to inccorrect variables and secret in test task definition. 

If I remove test from pipeline.yml then prod gets deployed with out any issue.


Somehow test env is not receving the right secrets and variables.

Thanks you for you great work on copilot.

### PR DESCRIPTION
**Pull request by iamhopaul123**
fixes #1535, fixes #1458

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iamhopaul123** [comment]
integ test as well as manual e2e test pass

**Review by efekarakus — APPROVED** [review]
😍  thank you!

**Review by bvtujo — COMMENTED** [review]
Looks great! Do we need to update the buildspec anywhere, or should I go ahead and updated it in my outstanding buildspec PR to be merged in after package Execute()?

**Review by bvtujo — APPROVED** [review]

**Comment by efekarakus** [comment]
@bvtujo 
> Looks great! Do we need to update the buildspec anywhere, or should I go ahead and updated it in my outstanding buildspec PR to be merged in after package Execute()?

The buildspec does not need to be updated! The new version of the CLI that will be pulled by the buildspec will now emit the stack template with the environment name included in it. The users will have to run `pipeline update` so that the deploy actions read the artifacts from the correct locations!

**Pull request merged**
