### PR TITLE
fix(manifest): escape env var values while rendering CFN template

### LINKED ISSUE #1120: Env variable with value as "on" is converted to true
Currently I am deploying a service where there is an requirement for env variable which can take value as `on` or `off`. But when this service is being deployed, the container will have a boolean value `true` for `on` and `false` for `off`

Example:
```yaml
variables:                      
  ENV_KEY: on
```

The resulting container will have env as `ENV_KEY`: `true`

### LINKED ISSUE #1292: Specifiy a JSON environment variable results in failed deployment
Hello,

If I add a JSON string as a variable in my manifest the deployment fails:

```
variables:
  HASURA_GRAPHQL_JWT_SECRET: "{}"
```

Results in Model validation failed ("#/ContainerDefinitions/0/Environment/8/Value: expected type: String, found: JSONObject".)

I tried to escape the JSON, but the result is the same.

Where is the expected type taken from? Can I specify it?

copilot version: v0.2.0
macOS 10.15.4 (19E287)

Best regards,
Benedikt

### PR DESCRIPTION
**Pull request by efekarakus**
Use the %q verb (a double-quoted string safely escaped with Go syntax)
when writing env var values. This ensures that values like `"{}"` or
`on` are written as strings instead of a mapping or boolean object.

Fixes #1120, fixes #1292

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by efekarakus** [comment]
Added the "do-not-merge" label while running e2e tests.

**Comment by kohidave** [comment]
I kind of miss our golden file integ tests. They'd compare the packaged cf template to the expected cf template. That'd help with this class of error.

**Review by kohidave — APPROVED** [review]

**Review by huanjani — APPROVED** [review]

**Comment by efekarakus** [comment]
> I kind of miss our golden file integ tests. They'd compare the packaged cf template to the expected cf template. That'd help with this class of error.

I'll use `testdata/` while fixing the same bug for pipelines and add integ tests for both

**Review by bvtujo — APPROVED** [review]
LGTM!

**Pull request merged**
