### PR TITLE
feat(cli): include capacity provider in svc status

### PR DESCRIPTION
**Pull request by SoManyHs**
Final part of https://github.com/aws/copilot-cli/issues/2162

NOTE: the new `Capacity Provider` column is placed before the `Health Status` column due to weird spacing issues caused by colorizing the status field.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by SoManyHs** [comment]
Without Capacity Providers:
```
$ archer svc status
Found only one deployed service api in environment test
Service Status

  ACTIVE 2 / 2 running tasks (0 pending)

Last Deployment

  Updated At         6 minutes ago
  Task Definition    arn:aws:ecs:us-west-2:794715269151:task-definition/app-test-api:3

Task Status

  ID                Image Digest        Last Status         Started At          Stopped At          Capacity Provider    Health Status
  --                ------------        -----------         ----------          ----------          -----------------    -------------
  2c7fbed7          fba93b94            RUNNING             7 minutes ago       -                   -                    UNKNOWN
  8827aa36          fba93b94            RUNNING             7 minutes ago       -                   -                    UNKNOWN

Alarms

  Name              Condition           Last Updated        Health
  ----              ---------           ------------        ------
```

With Capacity Providers:
```
$ archer svc status
Found only one deployed service api in environment test
Service Status

  ACTIVE 3 / 3 running tasks (0 pending)

Last Deployment

  Updated At         28 minutes ago
  Task Definition    arn:aws:ecs:us-west-2:794715269151:task-definition/app-test-api:3

Task Status

  ID                Image Digest        Last Status         Started At          Stopped At          Capacity Provider    Health Status
  --                ------------        -----------         ----------          ----------          -----------------    -------------
  55f96eac          fba93b94            RUNNING             31 minutes ago      -                   FARGATE_SPOT         UNKNOWN
  627a22f4          fba93b94            RUNNING             31 minutes ago      -                   FARGATE_SPOT         UNKNOWN
  ad8338f9          fba93b94            RUNNING             31 minutes ago      -                   FARGATE_SPOT         UNKNOWN

Alarms

  Name                              Condition                         Last Updated        Health
  ----                              ---------                         ------------        ------
```

**Comment by SoManyHs** [comment]
Without Capacity Providers:
```
$ archer svc status
Found only one deployed service api in environment test
Service Status

  ACTIVE 2 / 2 running tasks (0 pending)

Last Deployment

  Updated At         6 minutes ago
  Task Definition    arn:aws:ecs:us-west-2:xxxxxxxxxxx:task-definition/app-test-api:3

Task Status

  ID                Image Digest        Last Status         Started At          Stopped At          Capacity Provider    Health Status
  --                ------------        -----------         ----------          ----------          -----------------    -------------
  2c7fbed7          fba93b94            RUNNING             7 minutes ago       -                   -                    UNKNOWN
  8827aa36          fba93b94            RUNNING             7 minutes ago       -                   -                    UNKNOWN

Alarms

  Name              Condition           Last Updated        Health
  ----              ---------           ------------        ------
```

With Capacity Providers:
```
$ archer svc status
Found only one deployed service api in environment test
Service Status

  ACTIVE 3 / 3 running tasks (0 pending)

Last Deployment

  Updated At         28 minutes ago
  Task Definition    arn:aws:ecs:us-west-2:xxxxxxxxxxx:task-definition/app-test-api:3

Task Status

  ID                Image Digest        Last Status         Started At          Stopped At          Capacity Provider    Health Status
  --                ------------        -----------         ----------          ----------          -----------------    -------------
  55f96eac          fba93b94            RUNNING             31 minutes ago      -                   FARGATE_SPOT         UNKNOWN
  627a22f4          fba93b94            RUNNING             31 minutes ago      -                   FARGATE_SPOT         UNKNOWN
  ad8338f9          fba93b94            RUNNING             31 minutes ago      -                   FARGATE_SPOT         UNKNOWN

Alarms

  Name                              Condition                         Last Updated        Health
  ----                              ---------                         ------------        ------
```

**Review by Lou1415926 — APPROVED** [review]
Looks great!! Let's :shipit:

**Review by huanjani — APPROVED** [review]
I think it kinda makes sense for Health Status to go at the end, anyway! Looks good!

**Pull request merged**
